name: "ğŸ› ï¸ Debug Export"

env:
  EXPORT_MODE: debug

on:
  push:
    branches:
      - main

jobs:
  static-checks:
    name: ğŸ§ª Static Checks
    uses: ./.github/workflows/static_checks.yml
    
  linux-build:
    name: ğŸ§ Linux
    needs: static-checks
    uses: ./.github/workflows/linux_build.yml   
        
