name: "Export-Debug CI"
on:
  push:
    branches:
      - main

env:
  GODOT_VERSION: 4.2.2
  EXPORT_NAME: game
  PROJECT_PATH: project

jobs:
  export:
    name: ${{ matrix.os }}-Export
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: ðŸªŸ Windows
            platform_name: "Windows Desktop"
            artifact_name: windows
            file_extension: .exe
          - os: ðŸ§ Linux
            platform_name: "Linux/X11"
            artifact_name: linux
            file_extension: .x86_64
          - os: ðŸ Mac
            platform_name: "macOS"
            artifact_name: mac
            file_extension: .zip

    container:
      image: barichello/godot-ci:4.2.2 

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

      - name: Build
        run: |
          mkdir -v -p build/${{ matrix.artifact_name }}
          cd $PROJECT_PATH
          godot --headless --verbose --export-debug "${{ matrix.platform_name }}" ../build/${{ matrix.artifact_name }}/$EXPORT_NAME${{ matrix.file_extension }}

      - name: Set Date
        run: echo "DATE=$(date +'%Y%m%d-%H%M')" >> $GITHUB_ENV

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}-${{ env.DATE }}-debug
          path: build/${{ matrix.artifact_name }}
