name: "üêß Linux"

on:
  workflow_call:
    inputs:
      export-mode:
        type: string
        required: true

jobs:
  linux-build:
    name: "üêß Linux"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Godot
        uses: chickensoft-games/setup-godot@v2
        with:
          version: "4.2.2"
          use-dotnet: false
          include-templates: true
          cache: false

      - name: Build Debug
        run: |
          mkdir -v -p build/linux
          cd project
          godot --headless --verbose --export-${{ inputs.export-mode }} "Linux/X11" ../build/linux/linux-${{ inputs.export-mode }}.x86-64

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: "linux-${{ inputs.export-mode }}"
          path: "build/linux"
        
